/**
 * @file Unified API Hooks Index
 * 
 * This file is auto-generated by OpenAPI codegen.
 * It exports all API hooks from the unified apiHooks.ts file.
 * 
 * Usage:
 * import { useGetAuthLoginQuery, useCreateUserMutation } from '@/lib/api'
 * 
 * To regenerate:
 * npm run codegen
 */

// Re-export all hooks from the auto-generated apiHooks file
export * from './apiHooks';
